---
- name: Retrive Password from CyberArk CCP
  hosts: localhost
  collections: 
    - cyberark.pas

  tasks:
    - name: Credential retrieval
      cyberark_credential:
        api_base_url: "{{ api_base_url }}"
        app_id: "{{ app_id }}"
        validate_certs: no
        query: "{{ query }}"
      register: result

    - name: debug
      debug:
        msg: "Content: {{ result.Content }}"