---
- name: Retrive Password from CyberArk CCP
  hosts: localhost
  gather_facts: no

  collections: 
    - cyberark.pas
  vars:
    - api_base_url: "https://10.77.66.135"
    - app_id: "AIMWebService"
    - query: "Safe=Window;Object=Operating System-WinServerLocal-10.77.66.142-test"

  tasks:
    - name: Credential retrieval
      cyberark_credential:
        api_base_url: "{{ api_base_url }}"
        app_id: "{{ app_id }}"
        validate_certs: no
        query: "{{ query }}"
      register: result
      ignore_errors: yes
      no_log: yes

    - name: debug
      debug:
        msg: "{{ result }}"
